### ISSUE TITLE
Help to provide example project

### ISSUE THREAD

**Issue by chungminhtu** [GemunIon/nestjs-sqs#124]
Hi, thank for wonderful library, I wanted this for long time.

I wish there could be an example project where I know how to config the full nest project.

For example some of variables I don't know where to import (SqsClient, sqs,  @Inject(SQS_SERVICE)...) 

and the topic name also not understandable from your readme: 
- client.emit(EVENT_NAME) but in clientProxy  @MessagePattern(MESSAGE_TYPE) and @EventPattern(EVENT_TYPE) 
=> so, a little bit confuse.

Could you help me to make it more clear so easier for other guys to implement.

**Comment by TrejGun** [comment]
Hi @chungminhtu 

please see `sqs.server.spec.ts` it has configured testing app with all variables set and message examples

**Comment by chungminhtu** [comment]
Thanks for quick reply,

If I want to test with local sqs using docker, what should I config in docker?

This is my docker-compose

```
  alpine-sqs:
    image: roribio16/alpine-sqs:latest
    container_name: alpine-sqs
    ports:
      - "9324:9324"
      - "9325:9325"
    stdin_open: true
    tty: true
```
